// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-build: https://github.com/rdavid/pam_logger/actions/workflows/build.yml/badge.svg
:img-hoc: https://hitsofcode.com/github/rdavid/pam_logger?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/pam_logger?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:url-actionlint: https://github.com/rhysd/actionlint
:url-build: https://github.com/rdavid/pam_logger/actions/workflows/build.yml
:url-checkmake: https://github.com/checkmake/checkmake
:url-conform: https://github.com/siderolabs/conform
:url-cppcheck: https://cppcheck.sourceforge.io
:url-cv: http://cv.rabkin.co.il
:url-hoc: https://hitsofcode.com/view/github/rdavid/pam_logger?branch=master
:url-license: https://github.com/rdavid/pam_logger/blob/master/LICENSES/0BSD.txt
:url-pam: https://github.com/linux-pam/linux-pam
:url-reuse: https://github.com/fsfe/reuse-action
:url-sudo-timeout: https://askubuntu.com/questions/636092/how-to-get-sudo-to-prompt-you-for-a-password-each-time
:url-typos: https://github.com/crate-ci/typos
:url-yamllint: https://github.com/adrienverge/yamllint
:url-zizmor: https://github.com/zizmorcore/zizmor

= PAM Logger

// The ASCII art is generated with figlet using the standard font:
//  figlet -f standard -w 79 'pam logger'
[,sh]
----
                                     _
             _ __   __ _ _ __ ___   | | ___   __ _  __ _  ___ _ __
            | '_ \ / _` | '_ ` _ \  | |/ _ \ / _` |/ _` |/ _ \ '__|
            | |_) | (_| | | | | | | | | (_) | (_| | (_| |  __/ |
            | .__/ \__,_|_| |_| |_| |_|\___/ \__, |\__, |\___|_|
            |_|                              |___/ |___/
----

[subs=attributes+]
++++
<div align="right">
<a href="{url-build}"><img src="{img-build}" alt="build"></a>
<a href="{url-hoc}"><img src="{img-hoc}" alt="hits of code"></a>
<a href="{url-license}"><img src="{img-license}" alt="license"></a>
</div>
++++

toc::[]

ifdef::pages-build[]
++++
<div id="repo-link">
  <a href="https://github.com/rdavid/pam_logger" aria-label="GitHub repository" target="_blank" rel="noopener">
    <svg viewBox="0 0 16 16" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>
    </svg>
  </a>
</div>
++++
endif::[]

== About

This project implements a Pluggable Authentication Module
({url-pam}[`PAM`]) that hooks into the `pam_sm_authenticate` API to capture
the username, password, process ID, and triggering command on every login.
The collected data is appended to `/tmp/pam_logger.log` in a structured
format for auditing and research.
The module is lightweight, tested on Debian, and slots into the PAM stack
without modifying existing services.

== Install

Disable the authentication timeout for `sudo`, as described in this
{url-sudo-timeout}[Ask Ubuntu answer].
Then add the module to the `sudo` PAM stack and install it:

[,sh]
----
sudo sed -i '2s/^/auth sufficient pam_logger.so/' /etc/pam.d/sudo
make install
----

From this point on, every `sudo` command logs to `/tmp/pam_logger.log`.

== Using

Run any `sudo` command, then inspect the log:

[,sh]
----
sudo ls
cat /tmp/pam_logger.log
----

Each authentication appends a single line:

[,sh]
----
user:david, pass:s3cr3t, pid:12345, cmd:sudo ls.
----

CAUTION: The module records the entered password in clear text in a
world-readable file under `/tmp`. Use it only for controlled auditing or
research, never on systems that handle real credentials.

== Build

The module builds with `make`:

[,sh]
----
make main     # compile main.o with -Wall -Wextra -Werror
make install  # link pam_logger.so into the PAM modules directory
----

Continuous integration compiles `main.c` with both `gcc` and `clang`, runs
the {url-cppcheck}[`cppcheck`] static analyzer, and applies the following
linters:
{url-actionlint}[`actionlint`],
{url-checkmake}[`checkmake`],
{url-conform}[`conform`],
{url-reuse}[`reuse`],
{url-typos}[`typos`],
{url-yamllint}[`yamllint`],
{url-zizmor}[`zizmor`].

== License

`pam_logger` belongs to {url-cv}[David Rabkin] and uses a
{url-license}[Zero-Clause BSD license].

ifdef::pages-build[]
++++
<footer id="site-footer">
  <div class="footer-left">
    <img src="favicon.svg" alt="" width="20" height="20">
    <span>pam_logger by <a href="http://cv.rabkin.co.il" target="_blank" rel="noopener">David Rabkin</a></span>
  </div>
  <div class="footer-links">
    <a href="https://github.com/rdavid/pam_logger" target="_blank" rel="noopener">GitHub</a>
    <a href="https://github.com/rdavid/pam_logger/blob/master/LICENSES/0BSD.txt" target="_blank" rel="noopener">0BSD License</a>
  </div>
</footer>
++++
endif::[]
