// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-build: https://github.com/rdavid/pam_logger/actions/workflows/build.yml/badge.svg
:img-hoc: https://hitsofcode.com/github/rdavid/pam_logger?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/pam_logger?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:url-actionlint: https://github.com/rhysd/actionlint
:url-build: https://github.com/rdavid/pam_logger/actions/workflows/build.yml
:url-checkmake: https://github.com/checkmake/checkmake
:url-cppcheck: https://cppcheck.sourceforge.io
:url-cv: http://cv.rabkin.co.il
:url-hoc: https://hitsofcode.com/view/github/rdavid/pam_logger?branch=master
:url-license: https://github.com/rdavid/pam_logger/blob/master/LICENSES/0BSD.txt
:url-pam: https://github.com/linux-pam/linux-pam
:url-reuse: https://github.com/fsfe/reuse-action
:url-sudo-timeout: https://askubuntu.com/questions/636092/how-to-get-sudo-to-prompt-you-for-a-password-each-time
:url-typos: https://github.com/crate-ci/typos
:url-yamllint: https://github.com/adrienverge/yamllint

= PAM Logger

// The ASCII art is generated with figlet using the standard font:
//  figlet -f standard -w 79 'pam logger'
[,sh]
----
                         _
 _ __   __ _ _ __ ___   | | ___   __ _  __ _  ___ _ __
| '_ \ / _` | '_ ` _ \  | |/ _ \ / _` |/ _` |/ _ \ '__|
| |_) | (_| | | | | | | | | (_) | (_| | (_| |  __/ |
| .__/ \__,_|_| |_| |_| |_|\___/ \__, |\__, |\___|_|
|_|                              |___/ |___/
----

image:{img-build}[build,link={url-build}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

This project implements a Pluggable Authentication Module
({url-pam}[`PAM`]) that hooks the `pam_sm_authenticate` API to capture
authentication details during login events: the username, the entered
password, the process ID, and the command that triggered authentication.
The collected data is appended to `/tmp/pam_logger.log` in a structured
format for auditing, research, and security monitoring.
This module is lightweight, tested on Debian, and integrates into
authentication workflows without modifying existing services.

== Install

Disable the authentication timeout for `sudo`, as described in this
{url-sudo-timeout}[Ask Ubuntu answer].
Configure the `sudo` PAM stack and install the module:

[,sh]
----
sudo sed -i '2s/^/auth sufficient pam_logger.so/' /etc/pam.d/sudo
make install
----

From this point on, all `sudo` commands log to `/tmp/pam_logger.log`.

== Using

Run any `sudo` command, then inspect the log:

[,sh]
----
sudo ls
cat /tmp/pam_logger.log
----

Each authentication appends a single line:

[,sh]
----
user:david, pass:s3cr3t, pid:12345, cmd:sudo ls.
----

CAUTION: The module records the entered password in clear text in a
world-readable file under `/tmp`. Use it only for controlled auditing or
research, never on systems handling real credentials.

== Build

The module builds with `make`:

[,sh]
----
make main     # compile main.o with -Wall -Wextra -Werror
make install  # link pam_logger.so into the PAM modules directory
----

Continuous integration compiles `main.c` with both `gcc` and `clang`, runs
the {url-cppcheck}[`cppcheck`] static analyzer, and applies the
{url-actionlint}[`actionlint`], {url-checkmake}[`checkmake`],
{url-reuse}[`reuse`], {url-typos}[`typos`], and {url-yamllint}[`yamllint`]
linters.

== License

`pam_logger` belongs to {url-cv}[David Rabkin] and uses a
{url-license}[Zero-Clause BSD license].
