# SPDX-FileCopyrightText: 2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: build
'on': [pull_request, push]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
      - uses: actions/checkout@v7.0.0
      - run: sudo apt-get update && sudo apt-get install --yes libpam0g-dev
      - run: make main CC=${{ matrix.cc }}
