# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: checkmake
'on':
  pull_request:
    paths: &paths
      - Makefile
  push:
    branches: [master]
    paths: *paths
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
defaults:
  run:
    shell: sh
env:
  CM_BIN: /usr/local/bin/checkmake
  CM_SHA: e2effb876913f3ee2caef0ba35f6202c5e8a3cd55a077d8d2b9ce2034257b6af
  CM_URL: https://github.com/checkmake/checkmake/releases/download/v0.3.2/checkmake-v0.3.2.linux.amd64 # yamllint disable-line
jobs:
  checkmake:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - id: cache
        uses: actions/cache@v6.1.0
        with:
          path: ${{ env.CM_BIN }}
          key: checkmake-0.3.2-${{ runner.os }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl --location --output "$CM_BIN" --silent "$CM_URL"
          echo "$CM_SHA  $CM_BIN" | sha256sum --check
          chmod +x "$CM_BIN"
      - run: "$CM_BIN Makefile"
